name: Manage versions

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
      - name: Bump Versions
        uses: michmich112/version-bumper@2d03d0a28bc5d10340be0a4a43d6d2a4c5ec0756
        with:
          options-file: "./.github/workflows/options.json"
          github-token: ${{ secrets.GITHUB_TOKEN }}


